# Generated by Django 5.0.2 on 2025-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0008_add_missing_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='detection_accuracy',
            name='user_trained',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
